# Generated by Django 3.0.3 on 2020-02-12 14:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='date',
            new_name='pub_date',
        ),
    ]
